version: "3"

services:
  netease:
    build: 
      context: .
      args:
        - API_SCHEME=http
        - API_URL=localhost:3000
        # - GHPROXY=https://ghproxy.com/
    container_name: netease
    restart: unless-stopped
    ports:
      - "6688:6688"
    environment:
      - PORT=6688
    depends_on:
      - netease_api

  netease_api:
    image: binaryify/netease_cloud_music_api
    container_name: netease_api
    restart: unless-stopped
    ports:
      - "3000:3000"
