name: Build Image
on: push
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Get version
            id: get_version
            if: startsWith(github.ref, 'refs/tags/')
            run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            if: startsWith(github.ref, 'refs/tags/')
            with:
              publish: true
              imageName: a76yyyy/netease_music_web # dockerid/imageName
              platform: linux/arm64,linux/amd64,linux/arm/v7 # 你准备构建的镜像平台
              tag: latest,${{ steps.get_version.outputs.VERSION }}
              dockerUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
              dockerPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword