name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/DockerHub-Description.yml
jobs:
  dockerHubDescription:
    if: startsWith(github.repository, 'a76yyyy/NeteaseMusicWeb-Docker')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: a76yyyy/netease_music_web
        short-description: ${{ github.event.repository.description }}